# Generated by Django 4.0.4 on 2022-04-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.CharField(max_length=255)),
                ('ISBN_number', models.CharField(max_length=255)),
                ('number_of_pages', models.CharField(max_length=255)),
                ('cover_link', models.ImageField(upload_to='images/')),
                ('pub_language', models.CharField(max_length=255)),
            ],
        ),
    ]
